import { firebaseConfig, isFirebaseConfigured } from './firebase-config.js?v=2';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getDatabase, onValue, ref, set } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js';

const $ = (id) => document.getElementById(id);
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character]);
const formatTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
let database = null; let status = 'waiting'; let question = 0; let topicId = ''; let topics = {}; let students = {}; let accessCode = ''; let authReady = false;
const starterTopic = { name: 'Transposition Techniques', questions: [{ text: 'What is the defining operation of a transposition cipher?', options: ['Rearranging the positions of plaintext symbols', 'Replacing every letter with a new symbol', 'Hashing plaintext into a fixed digest', 'Adding a random key to each character'], answer: 0, difficulty: 'EASY' }] };
topics = { transposition: starterTopic }; topicId = 'transposition';
const currentQuestions = () => topics[topicId]?.questions || [];
const sortedStudents = () => Object.values(students).sort((a, b) => b.score - a.score || a.totalTime - b.totalTime);
function ensurePasscodeControl() { if ($('quizAccessCode')) return; const heading = document.querySelector('.admin-heading > div'); const control = document.createElement('label'); control.className = 'quiz-code-control'; control.innerHTML = 'Quiz passcode<input id="quizAccessCode" type="text" maxlength="30" placeholder="Set passcode for students"><small id="quizCodeError"></small>'; heading.appendChild(control); $('quizAccessCode').addEventListener('input', (event) => { accessCode = event.target.value.trim(); }); }
function renderQuestion() { const item = currentQuestions()[Math.max(0, question - 1)]; $('adminQuestion').textContent = `${question} / ${currentQuestions().length}`; $('adminQuestionText').textContent = item ? item.text : 'Waiting for the host to start the quiz.'; $('adminDifficulty').textContent = item?.difficulty || 'EASY'; $('adminChoices').innerHTML = item ? item.options.map((option, index) => `<div class="admin-choice"><span>${String.fromCharCode(65 + index)}</span>${escapeHtml(option)}</div>`).join('') : ''; }
function render() { ensurePasscodeControl(); const roster = sortedStudents(); $('adminStatus').textContent = status; $('adminOnline').textContent = roster.filter((student) => student.online).length; $('adminAnswers').textContent = roster.reduce((total, student) => total + (student.answeredQuestions || 0), 0); $('adminUpdated').textContent = roster.length ? `Updated ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Waiting for activity'; $('activeTopicLabel').textContent = topics[topicId]?.name || 'No topic selected'; $('quizAccessCode').value = accessCode; $('adminLeaderboard').innerHTML = `<div class="leader-row head"><span>Rank</span><span>Student</span><span>Score</span><span>Answered</span><span>Time</span></div>${roster.length ? roster.map((student, index) => `<div class="leader-row"><span class="leader-rank">#${index + 1}</span><span>${escapeHtml(student.name)}<small class="muted"> ${escapeHtml(student.rollNo)}</small></span><span class="leader-score">${student.score} pts</span><span>${student.answeredQuestions || 0} / ${currentQuestions().length}</span><span>${formatTime(student.totalTime || 0)}</span></div>`).join('') : '<p class="muted">No students have joined yet.</p>'}`; renderQuestion(); }
function connect() { if (!isFirebaseConfigured) { $('liveConnection').textContent = 'Configure Firebase'; return; } try { const app = initializeApp(firebaseConfig); database = getDatabase(app); signInAnonymously(getAuth(app)).then(() => { authReady = true; $('liveConnection').textContent = 'Live Firebase'; }).catch(() => { $('liveConnection').textContent = 'Auth failed'; }); setTimeout(() => { if ($('liveConnection').textContent === 'Connecting...') $('liveConnection').textContent = 'Connection timeout'; }, 8000); onValue(ref(database, 'topics'), (snapshot) => { topics = snapshot.val() || {}; if (!Object.keys(topics).length) topics = { transposition: starterTopic }; if (!topics[topicId]) topicId = Object.keys(topics)[0] || ''; render(); }); onValue(ref(database, 'students'), (snapshot) => { students = snapshot.val() || {}; render(); }); onValue(ref(database, 'quiz'), (snapshot) => { const quiz = snapshot.val() || {}; status = quiz.status || 'waiting'; question = Number(quiz.currentQuestion || 0); topicId = topics[quiz.topicId] ? quiz.topicId : (topics[topicId] ? topicId : Object.keys(topics)[0] || ''); accessCode = String(quiz.accessCode || ''); render(); }); } catch { $('liveConnection').textContent = 'Firebase error'; } }
$('liveLoginForm').addEventListener('submit', (event) => { event.preventDefault(); if ($('livePassword').value.trim() === 'admin123') { $('liveLogin').classList.add('hidden'); $('liveDashboard').classList.remove('hidden'); render(); } else $('liveLoginError').textContent = 'Incorrect demonstration password.'; });
$('startQuizButton').addEventListener('click', () => { if (!topicId) topicId = Object.keys(topics)[0] || ''; if (!currentQuestions().length) return; if (!accessCode) { $('quizCodeError').textContent = 'Set a passcode before starting.'; $('quizAccessCode').focus(); return; } if (!authReady) { $('quizCodeError').textContent = 'Firebase authentication is not ready. Wait for Live Firebase.'; return; } $('quizCodeError').textContent = ''; const session = { status: 'Live', currentQuestion: 1, topicId, accessCode }; set(ref(database, 'quiz'), session).then(() => { status = 'Live'; question = 1; render(); }).catch(() => { $('quizCodeError').textContent = 'Firebase denied the session update. Check Realtime Database rules.'; }); });
$('pauseQuizButton').addEventListener('click', () => { status = status === 'Paused' ? 'Live' : 'Paused'; if (database) set(ref(database, 'quiz/status'), status); render(); });
$('nextQuestionButton').addEventListener('click', () => { if (question < currentQuestions().length) question += 1; if (database) set(ref(database, 'quiz/currentQuestion'), question); render(); });
$('endQuizButton').addEventListener('click', () => { status = 'Ended'; if (database) set(ref(database, 'quiz/status'), status); render(); });
render(); connect();
