import { firebaseConfig, isFirebaseConfigured } from './firebase-config.js?v=2';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getDatabase, onValue, ref, set } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js';

const $ = (id) => document.getElementById(id);
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character]);
let database = null; let topics = {}; let selectedTopicId = 'transposition'; let editingQuestionId = null;
const seedTopics = () => ({ transposition: { name: 'Transposition Techniques', questions: [{ text: 'What is the defining operation of a transposition cipher?', options: ['Rearranging the positions of plaintext symbols', 'Replacing every letter with a new symbol', 'Hashing plaintext into a fixed digest', 'Adding a random key to each character'], answer: 0, difficulty: 'EASY' }] } });
const questions = () => topics[selectedTopicId]?.questions || [];
const save = () => { if (database) set(ref(database, 'topics'), topics); $('topicSaveStatus').textContent = 'Saved just now'; setTimeout(() => { $('topicSaveStatus').textContent = 'Changes save automatically'; }, 1800); };
const clearForm = () => { editingQuestionId = null; $('questionForm').reset(); $('questionFormTitle').textContent = 'NEW QUESTION'; $('questionFormError').textContent = ''; };
function renderList() { const items = questions(); $('questionCount').textContent = items.length; $('questionList').innerHTML = items.length ? items.map((item, index) => `<div class="question-list-row"><span class="question-number">${String(index + 1).padStart(2, '0')}</span><span class="question-list-text">${escapeHtml(item.text)}</span><span class="question-list-actions"><button type="button" class="text-button" data-edit="${index}">Edit</button><button type="button" class="text-button danger-text" data-delete="${index}">Delete</button></span></div>`).join('') : '<p class="muted">No questions yet. Add the first one.</p>'; document.querySelectorAll('[data-edit]').forEach((button) => button.addEventListener('click', () => edit(Number(button.dataset.edit)))); document.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', () => remove(Number(button.dataset.delete)))); }
function renderTopics() { if (!Object.keys(topics).length) topics = seedTopics(); if (!topics[selectedTopicId]) selectedTopicId = Object.keys(topics)[0]; $('topicSelect').innerHTML = Object.entries(topics).map(([id, topic]) => `<option value="${escapeHtml(id)}">${escapeHtml(topic.name)}</option>`).join(''); $('topicSelect').value = selectedTopicId; renderList(); }
function edit(index) { const item = questions()[index]; if (!item) return; editingQuestionId = index; $('questionFormTitle').textContent = `EDIT QUESTION ${String(index + 1).padStart(2, '0')}`; $('questionTextInput').value = item.text; item.options.forEach((option, optionIndex) => { $(`option${optionIndex}Input`).value = option; }); $('correctAnswerInput').value = item.answer; $('difficultyInput').value = item.difficulty || 'EASY'; $('questionTextInput').focus(); }
function remove(index) { if (!confirm('Delete this question?')) return; topics[selectedTopicId].questions.splice(index, 1); clearForm(); save(); renderList(); }
function connect() { if (!isFirebaseConfigured) { $('managerConnection').textContent = 'Configure Firebase'; return; } try { const app = initializeApp(firebaseConfig); database = getDatabase(app); signInAnonymously(getAuth(app)).catch(() => { $('managerConnection').textContent = 'Auth failed'; }); onValue(ref(database, 'topics'), (snapshot) => { topics = snapshot.val() || {}; if (!Object.keys(topics).length) { topics = seedTopics(); save(); } renderTopics(); }); $('managerConnection').textContent = 'Live Firebase'; } catch { $('managerConnection').textContent = 'Firebase error'; } }
$('managerLoginForm').addEventListener('submit', (event) => { event.preventDefault(); if ($('managerPassword').value.trim() === 'admin123') { $('managerLogin').classList.add('hidden'); $('managerDashboard').classList.remove('hidden'); renderTopics(); } else $('managerLoginError').textContent = 'Incorrect demonstration password.'; });
$('topicSelect').addEventListener('change', (event) => { selectedTopicId = event.target.value; clearForm(); renderList(); });
$('newTopicForm').addEventListener('submit', (event) => { event.preventDefault(); const name = $('newTopicName').value.trim(); if (!name) return; const id = `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'topic'}-${Date.now()}`; topics[id] = { name, questions: [] }; selectedTopicId = id; $('newTopicName').value = ''; save(); renderTopics(); });
$('questionForm').addEventListener('submit', (event) => { event.preventDefault(); const text = $('questionTextInput').value.trim(); const options = [0, 1, 2, 3].map((index) => $(`option${index}Input`).value.trim()); if (!text || options.some((option) => !option)) { $('questionFormError').textContent = 'Enter a question and all four options.'; return; } const item = { text, options, answer: Number($('correctAnswerInput').value), difficulty: $('difficultyInput').value }; if (editingQuestionId === null) questions().push(item); else topics[selectedTopicId].questions[editingQuestionId] = item; save(); clearForm(); renderList(); });
$('cancelEditButton').addEventListener('click', clearForm);
renderTopics(); connect();
