import { firebaseConfig, isFirebaseConfigured } from './firebase-config.js?v=2';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getDatabase, onValue, ref, set } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js';

const questions = [
  { text: 'What is the defining operation of a transposition cipher?', options: ['Rearranging the positions of plaintext symbols', 'Replacing every letter with a new symbol', 'Hashing plaintext into a fixed digest', 'Adding a random key to each character'], answer: 0, difficulty: 'EASY' },
  { text: 'How does a transposition cipher differ from a substitution cipher?', options: ['Transposition changes positions; substitution changes symbols', 'Transposition always uses numbers; substitution uses letters', 'Substitution cannot use a key', 'There is no meaningful difference'], answer: 0, difficulty: 'EASY' },
  { text: 'In a Rail Fence cipher, plaintext is commonly written...', options: ['In a zigzag across multiple rails', 'In a square spiral', 'Backwards in one row', 'Using a frequency table'], answer: 0, difficulty: 'EASY' },
  { text: 'What controls the column order in a keyed columnar transposition?', options: ['The alphabetical order of key letters', 'The length of the ciphertext only', 'The first plaintext word', 'A hash digest'], answer: 0, difficulty: 'EASY' },
  { text: 'Which property remains unchanged after a pure transposition?', options: ['The frequency of each plaintext symbol', 'The order of every symbol', 'The plaintext length and symbol counts', 'The key value'], answer: 2, difficulty: 'MEDIUM' },
  { text: 'To decrypt a basic transposition cipher, the receiver must know...', options: ['The rearrangement or permutation used', 'The plaintext in advance', 'A substitution alphabet only', 'The sender’s password hash'], answer: 0, difficulty: 'EASY' },
  { text: 'A permutation in cryptography describes...', options: ['A rearrangement of positions', 'A random prime number', 'A letter frequency score', 'A message authentication tag'], answer: 0, difficulty: 'EASY' },
  { text: 'A common limitation of simple transposition ciphers is that they...', options: ['Preserve letter frequencies and can leak patterns', 'Always produce longer messages', 'Cannot be decrypted with a key', 'Only work on binary files'], answer: 0, difficulty: 'MEDIUM' },
  { text: 'Which attack is especially useful against a simple transposition cipher?', options: ['Trying likely keys and analyzing readable structure', 'Changing the operating system clock', 'Guessing a public certificate', 'Brute-forcing a hash salt only'], answer: 0, difficulty: 'MEDIUM' },
  { text: 'In columnar transposition, a message shorter than the grid is often handled by...', options: ['Padding empty cells or using an agreed irregular rule', 'Deleting the final word', 'Replacing spaces with passwords', 'Converting it to a hash'], answer: 0, difficulty: 'MEDIUM' },
  { text: 'What is the purpose of a key in a keyed transposition?', options: ['To select a repeatable permutation', 'To replace every character', 'To make the message longer', 'To remove all spaces permanently'], answer: 0, difficulty: 'EASY' },
  { text: 'Which combination generally provides stronger classical encryption?', options: ['Transposition combined with substitution', 'Transposition with no key', 'A shorter plaintext', 'Removing the ciphertext'], answer: 0, difficulty: 'MEDIUM' },
  { text: 'Why can frequency analysis still help attack transposition ciphers?', options: ['Symbol frequencies are preserved', 'The cipher reveals the key directly', 'Every symbol becomes unique', 'The ciphertext is always sorted'], answer: 0, difficulty: 'MEDIUM' },
  { text: 'A Rail Fence cipher with how many rails is most likely to preserve nearby character relationships?', options: ['Two rails', 'One hundred rails', 'Zero rails', 'A random number for every letter'], answer: 0, difficulty: 'MEDIUM' },
  { text: 'Transposition techniques are historically associated with...', options: ['Classical military and diplomatic communications', 'Modern GPU rendering only', 'Database indexing only', 'Password hashing standards'], answer: 0, difficulty: 'EASY' }
];

const state = { student: null, questionIndex: 0, score: 0, correct: 0, totalTime: 0, questionStarted: 0, submitted: false, timer: null, shuffledQuestions: [], shuffledOptions: [], students: {}, quizStatus: 'waiting', quizQuestion: 0 };
let firebaseAuth = null;
let firebaseDatabase = null;
const $ = (id) => document.getElementById(id);
const views = ['loginView', 'waitingView', 'quizView', 'resultView'];
const showView = (viewId) => views.forEach((id) => $(id).classList.toggle('hidden', id !== viewId));
const showToast = (message) => { const toast = $('toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); };
const formatTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
const shuffle = (items) => [...items].sort(() => Math.random() - 0.5);

function connectFirebase() {
  if (!isFirebaseConfigured) { $('connectionLabel').textContent = 'Firebase setup needed'; $('firebaseNotice').textContent = 'Add your Firebase Web config in firebase-config.js to join the live room.'; $('firebaseNotice').classList.add('error-notice'); $('loginForm').querySelector('button').disabled = true; return; }
  try {
    const app = initializeApp(firebaseConfig);
    firebaseAuth = getAuth(app);
    firebaseDatabase = getDatabase(app);
    signInAnonymously(firebaseAuth).then(() => { $('connectionLabel').textContent = 'Live Firebase'; $('firebaseNotice').textContent = 'Connected. Waiting for the host to open the room.'; }).catch(() => { $('connectionLabel').textContent = 'Auth failed'; $('firebaseNotice').textContent = 'Anonymous Firebase sign-in failed. Check Authentication settings.'; $('firebaseNotice').classList.add('error-notice'); });
    onValue(ref(firebaseDatabase, 'students'), (snapshot) => {
      state.students = snapshot.val() || {};
      renderLeaderboard();
    });
    onValue(ref(firebaseDatabase, 'quiz'), (snapshot) => { const quiz = snapshot.val() || {}; state.quizStatus = String(quiz.status || 'waiting').toLowerCase(); state.quizQuestion = Number(quiz.currentQuestion || 0); $('waitingStatus').textContent = state.quizStatus; if (state.quizStatus === 'live' && state.student && !$('quizView').classList.contains('hidden')) return; if (state.quizStatus === 'live' && state.student && !$('waitingView').classList.contains('hidden')) startQuiz(); if (state.quizStatus === 'ended' && state.student) finishQuiz(); });
  } catch (error) {
    $('connectionLabel').textContent = 'Firebase error'; $('firebaseNotice').textContent = 'Firebase could not be initialized. Check firebase-config.js.'; $('firebaseNotice').classList.add('error-notice'); $('loginForm').querySelector('button').disabled = true;
  }
}
function sortedStudents() { return Object.values(state.students).sort((a, b) => b.score - a.score || a.totalTime - b.totalTime); }
function renderLeaderboard(target = 'leaderboardList') { const list = $(target); if (!list) return; const students = sortedStudents(); list.innerHTML = students.length ? students.slice(0, 8).map((student, index) => `<div class="leader-row ${state.student && student.id === state.student.id ? 'current' : ''}"><span class="leader-rank">${String(index + 1).padStart(2, '0')}</span><span>${escapeHtml(student.name)}</span><span class="leader-score">${student.score} pts</span></div>`).join('') : '<p class="muted">No scores yet.</p>'; const myRank = state.student ? students.findIndex((student) => student.id === state.student.id) + 1 : 1; $('rankValue').textContent = `#${myRank || 1}`; $('rankTotal').textContent = `/ ${students.length || 1} student${students.length === 1 ? '' : 's'}`; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character]); }
function updateStudent(record) { state.student = record; if (firebaseDatabase) set(ref(firebaseDatabase, `students/${record.id}`), record); renderLeaderboard(); }
function startStudent(name, rollNo) { if (Object.values(state.students).some((student) => student.rollNo.toLowerCase() === rollNo.toLowerCase())) { $('loginError').textContent = 'That roll number is already in the room.'; return false; } state.student = { id: firebaseAuth.currentUser.uid, name, rollNo, score: 0, correctAnswers: 0, answeredQuestions: 0, totalTime: 0, online: true }; updateStudent(state.student); return true; }
function startQuiz() { state.questionIndex = 0; state.score = 0; state.correct = 0; state.totalTime = 0; state.shuffledQuestions = shuffle(questions); state.submitted = false; showView('quizView'); renderQuestion(); }
function renderQuestion() { clearInterval(state.timer); const question = state.shuffledQuestions[state.questionIndex]; state.shuffledOptions = shuffle(question.options.map((text, index) => ({ text, correct: index === question.answer }))); state.submitted = false; $('questionLabel').innerHTML = `Question ${String(state.questionIndex + 1).padStart(2, '0')} <span>/ ${state.shuffledQuestions.length}</span>`; $('questionText').textContent = question.text; $('difficultyLabel').textContent = question.difficulty; $('progressBar').style.width = `${(state.questionIndex / state.shuffledQuestions.length) * 100}%`; $('answerFeedback').textContent = ''; $('submitButton').disabled = true; $('optionsList').innerHTML = state.shuffledOptions.map((option, index) => `<label class="option" data-index="${index}"><input type="radio" name="answer" value="${index}"><span class="option-letter">${String.fromCharCode(65 + index)}</span><span>${escapeHtml(option.text)}</span></label>`).join(''); document.querySelectorAll('.option').forEach((option) => option.addEventListener('click', () => { if (state.submitted) return; document.querySelectorAll('.option').forEach((item) => item.classList.remove('selected')); option.classList.add('selected'); $('submitButton').disabled = false; })); state.questionStarted = Date.now(); let remaining = 15; $('timerLabel').textContent = `00:${String(remaining).padStart(2, '0')}`; state.timer = setInterval(() => { remaining -= 1; $('timerLabel').textContent = formatTime(remaining); if (remaining <= 0) { clearInterval(state.timer); submitAnswer(true); } }, 1000); renderLeaderboard(); }
function submitAnswer(timedOut = false) { if (state.submitted) return; state.submitted = true; clearInterval(state.timer); const selected = document.querySelector('input[name="answer"]:checked'); const elapsed = Math.max(1, Math.round((Date.now() - state.questionStarted) / 1000)); const selectedIndex = selected ? Number(selected.value) : -1; const correct = selectedIndex >= 0 && state.shuffledOptions[selectedIndex].correct; const points = correct ? 10 + (elapsed <= 5 ? 5 : elapsed <= 10 ? 3 : 0) : 0; state.score += points; state.correct += correct ? 1 : 0; state.totalTime += elapsed; document.querySelectorAll('.option').forEach((option, index) => { option.style.pointerEvents = 'none'; if (state.shuffledOptions[index].correct) option.classList.add('correct'); if (index === selectedIndex && !correct) option.classList.add('wrong'); }); $('answerFeedback').textContent = timedOut ? 'Time expired · 0 points' : correct ? `Correct · +${points} points${points > 10 ? ' speed bonus' : ''}` : 'Not quite · 0 points'; $('submitButton').disabled = true; updateStudent({ ...state.student, score: state.score, correctAnswers: state.correct, answeredQuestions: state.questionIndex + 1, totalTime: state.totalTime, online: true }); if (firebaseDatabase) set(ref(firebaseDatabase, `answers/${state.student.id}/question-${state.questionIndex + 1}`), { selectedAnswer: selectedIndex, correct, timeTaken: elapsed, score: points }); renderLeaderboard(); setTimeout(() => { if (state.questionIndex >= state.shuffledQuestions.length - 1) finishQuiz(); else { state.questionIndex += 1; renderQuestion(); } }, 1300); }
function finishQuiz() { clearInterval(state.timer); $('progressBar').style.width = '100%'; const students = sortedStudents(); const rank = students.findIndex((student) => student.id === state.student.id) + 1; $('resultName').textContent = `${state.student.name}.`; $('resultScore').textContent = state.score; $('resultRank').textContent = `Final rank #${rank || 1}`; $('resultCorrect').textContent = `${state.correct} / ${state.shuffledQuestions.length}`; $('resultAccuracy').textContent = `${Math.round((state.correct / state.shuffledQuestions.length) * 100)}%`; $('resultTime').textContent = formatTime(state.totalTime); $('resultParticipants').textContent = students.length; renderFinalLeaderboard(students); showView('resultView'); }
function renderFinalLeaderboard(students) { const top = students.slice(0, 3); const podium = top.length ? `<div class="podium">${[top[1], top[0], top[2]].map((student, index) => student ? `<div class="podium-item ${index === 1 ? 'top' : ''}"><div class="medal">${index === 1 ? '🥇' : index === 0 ? '🥈' : '🥉'}</div><strong>${escapeHtml(student.name)}</strong><span>${student.score} pts</span></div>` : '<div></div>').join('')}</div>` : ''; const rows = students.map((student, index) => `<tr class="${state.student && student.id === state.student.id ? 'current' : ''}"><td>#${index + 1}</td><td>${escapeHtml(student.name)}</td><td>${escapeHtml(student.rollNo)}</td><td>${student.score}</td><td>${Math.round((student.correctAnswers / Math.max(1, student.answeredQuestions)) * 100)}%</td><td>${formatTime(student.totalTime)}</td></tr>`).join(''); $('finalLeaderboard').innerHTML = `${podium}<table class="final-table"><thead><tr><th>RANK</th><th>STUDENT</th><th>ROLL NO</th><th>SCORE</th><th>ACCURACY</th><th>TIME</th></tr></thead><tbody>${rows}</tbody></table>`; }

$('loginForm').addEventListener('submit', (event) => { event.preventDefault(); $('loginError').textContent = ''; const name = $('studentName').value.trim(); const rollNo = $('rollNumber').value.trim(); if (!name || !rollNo) { $('loginError').textContent = 'Both fields are required to join.'; return; } if (!firebaseAuth || !firebaseAuth.currentUser) { $('loginError').textContent = 'Live connection is not ready yet.'; return; } if (startStudent(name, rollNo)) { showView('waitingView'); $('waitingParticipants').textContent = sortedStudents().length; showToast('You joined the live room.'); } });
if ($('submitButton')) $('submitButton').addEventListener('click', () => submitAnswer(false));
if ($('restartButton')) $('restartButton').addEventListener('click', () => { clearInterval(state.timer); showView('loginView'); });
window.addEventListener('online', () => { if (isFirebaseConfigured) connectFirebase(); });
if (isFirebaseConfigured) connectFirebase(); else connectFirebase();
// Client-side protections improve the demo experience but are not secure anti-cheating controls.
// Production scoring must be validated by trusted server-side code or Firebase security rules.
